name: 'Prepare Sisyphus'
description: 'Prepare "gradle.properties" needed by sisyphus build.'
inputs:
  developer:
    description: 'Sisyphus developer name.'
    required: false

  snapshot-repositories:
    description: 'Repositories to push snapshot artifact.'
    required: false
  release-repositories:
    description: 'Repositories to push release artifact.'
    required: false

  docker-repositories:
    description: 'Repositories to push docker images.'
    required: false
  config-repositories:
    description: 'Repositories to resolve config artifact dependencise.'
    required: false
  dependency-repositories:
    description: 'Repositories to resolve dependencise.'
    required: false

  config-artifacts:
    description: 'Config artifacts.'
    required: false

  gradle-portal-key:
    description: 'Key used for publishing plugin to gradle portal.'
    required: false
  gradle-portal-secret:
    description: 'Secret used for publishing plugin to gradle portal.'
    required: false

  gpg-keyname:
    description: 'Gnupg key name for signing.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'